name: pytest
run-name: ${{ github.actor }} is running tests
on:
  pull_request:
    paths:
      - '**.py'
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: export OPENAI_API_KEY="pytest"
    - run: pip install -r requirements.txt
    - run: pip install pytest pytest-env
    - run: pytest tests/

